export const navLinks = [
  {
    label: "Home",
    route: "/",
    icon: "/assets/icons/home.svg",
  },
  {
    label: "Training",
    route: "/training",
    icon: "/assets/icons/dumbbell.svg",
  },
  {
    label: "Nutrition",
    route: "/nutrition",
    icon: "/assets/icons/nutrition.svg",
  },
  {
    label: "Recovery",
    route: "/Recovery",
    icon: "/assets/icons/meditation.svg",
  },
  {
    label: "Profile",
    route: "/profile",
    icon: "/assets/icons/profile.svg",
  },
  {
    label: "Buy Credits",
    route: "/credits",
    icon: "/assets/icons/bag.svg",
  },
];

export const sportOptions = {
  soccer: "soccer",
  basketball: "basketball",
  tennis: "tennis",
  golf: "golf",
  cricket: "cricket",
  rugby: "rugby",
  baseball: "baseball",
  volleyball: "volleyball",
  iceHockey: "ice hockey",
  swimming: "swimming",
  cycling: "cycling",
  athletics: "athletics",
  boxing: "boxing",
  kickBoxing: "kick boxing",
  skiing: "skiing",
  snowboarding: "snowboarding",
  surfing: "surfing",
  skateboarding: "skateboarding",
  gymnastics: "gymnastics",
  wrestling: "wrestling",
  martialArts: "martial arts",
  tableTennis: "table tennis",
  badminton: "badminton",
  squash: "squash",
  rowing: "rowing",
  sailing: "sailing",
  archery: "archery",
  fencing: "fencing",
  climbing: "climbing",
  horseRacing: "horse racing",
  motorRacing: "motor racing",
};

export const levelOptions = ["beginner", "intermediate", "advanced", "expert"];

export const ageOptions = {
  0: "0",
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5",
  6: "6",
  7: "7",
  8: "8",
  9: "9",
  10: "10",
  11: "11",
  12: "12",
  13: "13",
  14: "14",
  15: "15",
  16: "16",
  17: "17",
  18: "18",
  19: "19",
  20: "20",
  21: "21",
  22: "22",
  23: "23",
  24: "24",
  25: "25",
  26: "26",
  27: "27",
  28: "28",
  29: "29",
  30: "30",
  31: "31",
  32: "32",
  33: "33",
  34: "34",
  35: "35",
  36: "36",
  37: "37",
  38: "38",
  39: "39",
  40: "40",
  41: "41",
  42: "42",
  43: "43",
  44: "44",
  45: "45",
  46: "46",
  47: "47",
  48: "48",
  49: "49",
  50: "50",
  51: "51",
  52: "52",
  53: "53",
  54: "54",
  55: "55",
  56: "56",
  57: "57",
  58: "58",
  59: "59",
  60: "60",
  61: "61",
  62: "62",
  63: "63",
  64: "64",
  65: "65",
  66: "66",
  67: "67",
  68: "68",
  69: "69",
  70: "70",
  71: "71",
  72: "72",
  73: "73",
  74: "74",
  75: "75",
  76: "76",
  77: "77",
  78: "78",
  79: "79",
  80: "80",
  81: "81",
  82: "82",
  83: "83",
  84: "84",
  85: "85",
  86: "86",
  87: "87",
  88: "88",
  89: "89",
  90: "90",
  91: "91",
  92: "92",
  93: "93",
  94: "94",
  95: "95",
  96: "96",
  97: "97",
  98: "98",
  99: "99",
  100: "100",
};

export const trainingPlans = [
  {
    author: {
      _id: "1",
      firstName: "Peter",
      lastName: "Pan",
    },
    numberOfWeeks: 8,
    sport: "Soccer",
    skillLevel: "Advanced",
    daysOfTraining: ["Tuesday", "Thursday", "Saturday"],
    exercisesByDay: {
      Tuesday: ["Passing drills", "Shooting practice"],
      Thursday: ["Tactical exercises", "Conditioning drills"],
      Saturday: ["Scrimmage", "Set-piece practice"],
    },
  },
  {
    author: {
      _id: "2",
      firstName: "Alice",
      lastName: "Wonderland",
    },
    numberOfWeeks: 6,
    sport: "Basketball",
    skillLevel: "Intermediate",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Dribbling drills", "Shooting practice"],
      Wednesday: ["Defensive drills", "Passing drills"],
      Friday: ["Scrimmage", "Conditioning drills"],
    },
  },
  {
    author: {
      _id: "3",
      firstName: "John",
      lastName: "Doe",
    },
    numberOfWeeks: 10,
    sport: "Tennis",
    skillLevel: "Beginner",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Forehand practice", "Backhand drills"],
      Wednesday: ["Serve practice", "Footwork exercises"],
      Friday: ["Volleys practice", "Match simulation"],
    },
  },
  // Add 10 more training plans here...
  {
    author: {
      _id: "4",
      firstName: "Emma",
      lastName: "Smith",
    },
    numberOfWeeks: 8,
    sport: "Swimming",
    skillLevel: "Advanced",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Freestyle technique", "Breaststroke drills"],
      Wednesday: ["Backstroke drills", "Endurance training"],
      Friday: ["Butterfly technique", "Sprint intervals"],
    },
  },
  {
    author: {
      _id: "5",
      firstName: "Michael",
      lastName: "Johnson",
    },
    numberOfWeeks: 12,
    sport: "Running",
    skillLevel: "Intermediate",
    daysOfTraining: ["Tuesday", "Thursday", "Saturday"],
    exercisesByDay: {
      Tuesday: ["Long run", "Interval training"],
      Thursday: ["Tempo run", "Hill sprints"],
      Saturday: ["Fartlek", "Recovery run"],
    },
  },
  {
    author: {
      _id: "6",
      firstName: "Sarah",
      lastName: "Wilson",
    },
    numberOfWeeks: 6,
    sport: "Cycling",
    skillLevel: "Beginner",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Road biking", "Hill climbs"],
      Wednesday: ["Sprints", "Endurance rides"],
      Friday: ["Bike handling skills", "Recovery ride"],
    },
  },
  {
    author: {
      _id: "7",
      firstName: "David",
      lastName: "Thompson",
    },
    numberOfWeeks: 8,
    sport: "Gymnastics",
    skillLevel: "Advanced",
    daysOfTraining: ["Tuesday", "Thursday", "Saturday"],
    exercisesByDay: {
      Tuesday: ["Balance beam routines", "Floor exercises"],
      Thursday: ["Vault drills", "Parallel bars"],
      Saturday: ["High bar routines", "Trampoline practice"],
    },
  },
  {
    author: {
      _id: "8",
      firstName: "Jennifer",
      lastName: "Brown",
    },
    numberOfWeeks: 10,
    sport: "Yoga",
    skillLevel: "Intermediate",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Sun salutations", "Standing poses"],
      Wednesday: ["Seated poses", "Twists"],
      Friday: ["Backbends", "Relaxation techniques"],
    },
  },
  {
    author: {
      _id: "9",
      firstName: "Robert",
      lastName: "Miller",
    },
    numberOfWeeks: 12,
    sport: "Boxing",
    skillLevel: "Advanced",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Shadow boxing", "Heavy bag work"],
      Wednesday: ["Sparring", "Speed bag drills"],
      Friday: ["Conditioning circuit", "Strategy analysis"],
    },
  },
  {
    author: {
      _id: "10",
      firstName: "Emily",
      lastName: "Garcia",
    },
    numberOfWeeks: 6,
    sport: "Martial Arts",
    skillLevel: "Intermediate",
    daysOfTraining: ["Tuesday", "Thursday", "Saturday"],
    exercisesByDay: {
      Tuesday: ["Forms practice", "Sparring drills"],
      Thursday: ["Technique refinement", "Weapons training"],
      Saturday: ["Self-defense scenarios", "Mental conditioning"],
    },
  },
  {
    author: {
      _id: "11",
      firstName: "James",
      lastName: "Jones",
    },
    numberOfWeeks: 10,
    sport: "Golf",
    skillLevel: "Advanced",
    daysOfTraining: ["Monday", "Wednesday", "Friday"],
    exercisesByDay: {
      Monday: ["Driving range session", "Putting drills"],
      Wednesday: ["Iron play practice", "Short game drills"],
      Friday: ["Course management", "Mental game exercises"],
    },
  },
];
